### ISSUE TITLE
Error message when no element to render on

### ISSUE THREAD

**Issue by slolo2000** [lindell/JsBarcode#101] opened 2016-09-21 09:18 UTC
Hello,

When there is no barcode to generate on the html page, the plugin send the following error: "Uncaught NoElementException: No element to render on."

As it is not only a simple warning in debug console but a real blocking error, is there any way to avoid it without the need of a try cacth block?

**Comment by lindell** [comment] 2016-09-21 09:22
The error was intended (at first). But since our discussion on email I know you want to use it with the `.init()` function.

It should not be required to do it like that since you might want to use it on every page of a website that might use barcodes. Marking this as a bug that should be fixed.

**Comment by lindell** [comment] 2016-09-27 17:47
[v3.5.1](https://github.com/lindell/JsBarcode/releases/tag/v3.5.1) should fix the problem. Please confirm this is working.

**Comment by slolo2000** [comment] 2016-09-27 19:22
Hello,

I can confirm that is works perfectly.

Thanks a lot for your hard work.
You are my hero!

Have a nice day and see you soon.


-------- Message d'origine --------
De : Johan Lindell <notifications@github.com>
Date : 27/09/2016 19:47 (GMT+01:00)
À : lindell/JsBarcode <JsBarcode@noreply.github.com>
Cc : slolo2000 <slolo2000@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [lindell/JsBarcode] Error message when no element to render on (#101)


v3.5.1<https://github.com/lindell/JsBarcode/releases/tag/v3.5.1> should fix the problem. Please confirm this is working.

-

**Comment by lindell** [comment] 2016-09-27 19:43
Perfect :+1: Closing the issue.

**Closed by lindell** 2016-09-27 19:43 UTC
Labels: Bug

**Comment by DanielFrugoni-dev** [comment] 2020-07-11 23:29
There is no way I can make work, Im using Angular + Electron + Handlebars . Have any one try something like that ? Thx

**Comment by mwasimuke** [comment] 2020-11-30 13:57
Hello! I also have the same error but i am not yet solve it, "no element to render on" . I need help!

**Comment by liusir-hub** [comment] 2020-12-16 10:53
Hello! I also have the same error but i am not yet solve it, "no element to render on"

**Comment by damikun** [comment] 2020-12-31 16:23
Error persist mainly if you import and use it under React..
