### ISSUE TITLE
svg sometimes not visible on mobile

### ISSUE THREAD

**Issue by RossellaFer** [lindell/JsBarcode#339] opened 2020-07-27 07:18 UTC
I have been using JsBarcode in my project and it has been working very well. I have, however, some users that report not being able to see the barcode at all from mobile. Some are Android users, some are iOS users, some are viewing the website via an app. 

Have there been any reports of the svg file not being rendered on mobile or being maybe cached? Other svg files on the same page are being rendered, without any issues, for these users, so I am thinking maybe there is something wrong in my code implementation. 

This is in my HTML
<svg class="bc-target"></svg>

```
   jsBarcode(".bc-target", userBarcode, {
            format: "EAN13",
            displayValue: true,
            width: 3.3,
            flat: true,
            textAlign: "left",
            text: `CODE ID: ${userBarcode}`,
            font: "Helvetica",
            textMargin: 15,
            fontSize: 13
        });
```

Should I specify `xmlns="http://www.w3.org/2000/svg" version="1.1"` in the HTML maybe? 

Thank you in advance for your help!

**Comment by lindell** [comment] 2020-07-27 08:55
I've not heard of similar reports before. Do you have a more detailed explanation of when this happens other than "Some are Android users, some are iOS users"? Is there a specific browser or specific OS versions where the problem happens.

Without a way to reproduce the problem, there is, unfortunately, no way of me to help you.

If the problem is not with the rendering. Are you sure that the `userBarcode` variable is a valid EAN13 number?

**Comment by lindell** [comment] 2020-07-27 08:57
Another comment on the snippet, using bar widths that is not integers (`3.3`) will cause problems for people with not high resolution devices.

**Comment by RossellaFer** [comment] 2020-07-27 09:30
One report was for a user with iPhoneXR, iOS13.5 and using Safari, however I don't have more information on the Android devices. I haven't been able to reproduce the issue myself, but I wanted to ask in case there were other similar reports. 

The userBarcode is a valid number because the barcode appears after refreshing the page several times or logging out / logging back in the account and visiting the same page.

Thanks for catching the bar widths error - could this cause an intermittent issue or would the user not be able to see the barcode at all?

**Comment by lindell** [comment] 2020-07-27 09:46
> One report was for a user with iPhoneXR, iOS13.5 and using Safari, however I don't have more information on the Android devices. I haven't been able to reproduce the issue myself, but I wanted to ask in case there were other similar reports.

If you find any way of reproducing the error, please come back with it and I will try to debug it :) But right now I can't do anything more and will, therefore, close the issue (but please open if you get more information).

> The userBarcode is a valid number because the barcode appears after refreshing the page several times or logging out / logging back in the account and visiting the same page.

And you are sure this is the case for all values of `userBarcode`. EAN13 is almost exclusively used to identify a specific retail product. The number is always 13 digits with the last digit being the EAN13 checksum? https://en.wikipedia.org/wiki/International_Article_Number#Calculation_of_checksum_digit
(Or 12 digits and since the checksum is then calculated automatically)

> Thanks for catching the bar widths error - could this cause an intermittent issue or would the user not be able to see the barcode at all?

This will produce blurry barcodes, but they should still be visible.

**Closed by lindell** 2020-07-27 09:46 UTC
