### ISSUE TITLE
Invalid regular expression: /^[ Range out of order in character class

### ISSUE THREAD

**Issue by sred36** [lindell/JsBarcode#381] opened 2021-08-09 12:51 UTC
JsBarcode("#barcode", "c5862dd0-3acf-4b62-9de3-39cad9b4e5bc", {format: "CODE128"}); //But you can still specify it

i just passed this c5862dd0-3acf-4b62-9de3-39cad9b4e5bc, i am getting error invalid regular expression

**Comment by lindell** [comment] 2021-08-09 13:35
Duplicate of #239 #163 ...

**Closed by lindell** 2021-08-09 13:35 UTC
