### ISSUE TITLE
"Renderer is not a constructor"

### ISSUE THREAD

**Issue by Scheder** [lindell/JsBarcode#96] opened 2016-08-09 15:05 UTC
This is not a direct issue for us, but to help you improve your code, I thought I'd share something I found. We are getting the Exception "i is not a constructor". You can safely catch and ignore the exception, and everything seems to work fine, but it is still there.

My code now is the following:

```
try {
	JsBarcode(imgID, barValue, {format:barFormat, displayValue:showValue, fontSize:parseInt(barFont), width:parseInt(barWidth), height:parseInt(barHeight), ratio:0.8});
} catch (err) {
	jslog("Error when using JsBarcode: " + err.message);
	//There is an error in JsBarcode we need to ignore (ie: i is not a constructor)
}
```

**Comment by lindell** [comment] 2016-08-09 15:16
This is strange. I'm running this exact code ()

**Comment by lindell** [comment] 2016-08-09 15:18
Thanks for reporting.

This is strange since I don't get any error when doing this (with CODE128, displayValue:true ...). Is this always generating the error and on what platforms?

**Comment by lindell** [comment] 2016-08-09 15:20
And if you are using the non minfied version. On what line in the code is it giving the error?

**Comment by Scheder** [comment] 2016-08-09 15:31
Pretty much always and I'm only using EAN13. I'm on Chrome and have not tried the non minified version yet. Though, I am about to leave the office now and will not be with this client until next Tuesday, so will not be able to update this issue before that. Sorry about that.

**Comment by lindell** [comment] 2016-08-09 15:37
No problem. But would be interesting to know what could cause this. Thanks for the feedback.

**Comment by wickedsp1d3r** [comment] 2016-08-11 10:37
Hello,

I have the same issue:

![err](https://cloud.githubusercontent.com/assets/1852854/17586180/bd750328-5fc8-11e6-83cf-374c3d9f598f.png)

**Comment by lindell** [comment] 2016-08-11 10:41
Thanks for the information on the issue.

What are you rendering on @wickedsp1d3r ? SVG / Canvas / img and does this happen for all of them?

**Comment by lindell** [comment] 2016-08-11 11:03
And what version of JsBarcode are you using?

**Comment by wickedsp1d3r** [comment] 2016-08-11 11:18
I used it with canvas. I just tried it with SVG and image and the error remains.
I am using the latest version (v3.3.20).

**Comment by lindell** [comment] 2016-08-11 11:22
Is it happening with all types of options? Or what options are you using right now?

**Comment by wickedsp1d3r** [comment] 2016-08-11 11:33
Even using it like this is generating the error: `JsBarcode('#barcode', 'Hi!');`
But usually I am using it like this:
```
JsBarcode('#barcode', number, {
    displayValue: true
});
```

**Comment by lindell** [comment] 2016-08-11 11:51
Something is apparently wrong. But I can't reproduce the error.

Is this working for you? http://codepen.io/lindell/pen/grkZGQ

**Comment by lindell** [comment] 2016-08-16 14:47
Ping @Scheder and @wickedsp1d3r

**Comment by Scheder** [comment] 2016-08-17 09:14
Yes that's working. The error also happens after most of the things are done, because the label renders and prints just fine. Though, on your page I can render multiple labels without the error popping up. On my page I need to capture and ignore the error.

I'm using svg as well.

I'm not really a js guru, but maybe we are using an older version that does not have the renderer?

**Comment by lindell** [comment] 2016-08-17 09:24
@Scheder It seems like this occur on the newest version as well.

@wickedsp1d3r wrote:
>I am using the latest version (v3.3.20).

The problem is that I cannot reproduce the error. If there is any way you (or anyone) could link to a place where this error occur I could troubleshot the error. Without it I don't even know where to start.

**Comment by Scheder** [comment] 2016-08-17 12:17
I mean, an older version of Javascript. I'm assuming you did not wrote the "Renderer", otherwise it would be packaged in the minimised version, right? That would mean it is part of the standard js libraries? As I'm (probably) not using the javascript engine from the browsers, but a custom version, it might just not have the Renderer? 

Might be wrong though. 

As I'm working in an environment that requires logging in, I can't give you access or simulate the environment. I hope wicked can help you out there. Sorry about that.

**Comment by lindell** [comment] 2016-08-17 13:47
That should not be the case. "Renderer" is the classes that generate the binary representation of the barcode. It has nothing to do with javascript.

I transpile the code from ES6 to ES5 and just verified that it runs on IE9 and above.

No problem, hopefully somebody else can give a way to reproduce the error.

**Comment by rmachielse** [comment] 2016-09-02 10:13
@lindell I am seeing the same error. I have downgraded the version until the error disappeared and the problem seems to be introduced in version 3.3.7.

The error message is a little different in that version:
```
JsBarcode.all.js:826 Uncaught TypeError: renderer is not a function
```

I also noticed (with a breakpoint) that the image is being rendered multiple times. The first time it renders with a CanvasRenderer and the second time the renderer is undefined.

**Comment by lindell** [comment] 2016-09-02 11:49
Thanks for the information!

Is there any way you could create an environment where I can reproduce the error (hosted or like a zip file).

**Comment by rmachielse** [comment] 2016-09-02 15:26
@lindell I think I know what is causing the problem. I couldn't get the issue reproduced in a codepen snippet or something, so I started to do some digging myself.

I discovered that the are some places where you iterate over an array using a for loop. That would be a normal thing in plain javascript, however in my case, I am using this library inside an [Ember.js](emberjs.com) project. Ember.js extends the prototype of `Array` with a lot of extra functions, somehow causing extra keys.

In a plain javascript console, iterating over array keys looks like this:

![schermafbeelding 2016-09-02 om 17 16 01](https://cloud.githubusercontent.com/assets/2470404/18208752/fe9d36f8-7130-11e6-94e3-d8cef3986513.png)

However, in an Ember.js project, it looks like this:

![schermafbeelding 2016-09-02 om 17 15 51](https://cloud.githubusercontent.com/assets/2470404/18208756/011cc448-7131-11e6-96c1-262b23e939d2.png)

Finally, this causes this location in your project to fail:

![schermafbeelding 2016-09-02 om 17 15 34](https://cloud.githubusercontent.com/assets/2470404/18208759/0386b5ae-7131-11e6-94c8-1b2065cd13a3.png)

That also explains why the barcode is still rendered (on the first iteration) and why it is rendering more then once (for each key).

Probably the other people that are having this problem are also using a library that manipulates the array prototype. This is probably an example of why prototype extensions are a bad idea haha. However, this could be fixed by using something like this to iterate (in es6):

```
this._renderProperties.forEach((renderProperties) => {
  render(renderProperties, ...);
});
```

So, here is a codepen example that does reproduce the issue: http://codepen.io/anon/pen/EgxLBB

**Comment by lindell** [comment] 2016-09-02 16:00
That is absolutely the reason! I know to not loop over array with `for in` but sometimes you do the simplest thing you know are going to work (on your machine).

I will patch the issue sometime this weekend.

Thanks very much for the assistance!

**Comment by lindell** [comment] 2016-09-03 09:29
Can you @rmachielse (or someone else) verify if this works in your environment?

[JsBarcode.all.js](https://gist.githubusercontent.com/lindell/762f3477d2fca78b4d519713db7d5696/raw/3bb581d73d0f59c4b2d218f45b8ea0df8e8b9dd0/JsBarcode.all.js)

**Comment by rmachielse** [comment] 2016-09-03 12:47
@lindell I have just tested your file in my environment and I can confirm that the issue seems to be fixed!

Thank you for your quick response and action!

**Comment by lindell** [comment] 2016-09-03 14:37
Perfect!
I released [3.3.23](https://github.com/lindell/JsBarcode/releases/tag/v3.3.23) now.
Closing the issue.

**Closed by lindell** 2016-09-03 14:37 UTC
Labels: Awaiting More Feedback, Bug

**Comment by rmachielse** [comment] 2016-09-03 21:13
@lindell great, thanks!

**Comment by angelov-a** [comment] 2019-02-08 19:42
Hello,

I'm experiencing the same issue when using with webpack:

`TypeError: "Encoder is not a constructor"`
`encode webpack-internal:///./node_modules/jsbarcode/lib/index.js:61:17`
`JsBarcode webpack-internal:///./node_modules/jsbarcode/lib/index.js:47:25`

It appears that the default `options` object which is passed to `encode()` does not contain an `encoder` member.
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var defaults = {
  width: 2,
  height: 100,
  format: 'auto',
  displayValue: true,
  fontOptions: '',
  font: 'monospace',
  text: undefined,
  textAlign: 'center',
  textPosition: 'bottom',
  textMargin: 2,
  fontSize: 20,
  background: '#ffffff',
  lineColor: '#000000',
  margin: 10,
  marginTop: undefined,
  marginBottom: undefined,
  marginLeft: undefined,
  marginRight: undefined,
  valid: function valid() {}
};
var _default = defaults;
exports.default = _default;
```
