### ISSUE TITLE
Regular expression error: JsBarcode.all.min.js:2 Uncaught SyntaxError: Invalid regular expression: /^[-_Ãˆ-Ã]*/: Range out of order in character class

### ISSUE THREAD

**Issue by alanzhaonys** [lindell/JsBarcode#239] opened 2018-04-09 06:38 UTC
I am getting:

```
JsBarcode.all.min.js:2 Uncaught SyntaxError: Invalid regular expression: /^[-_Ãˆ-Ã]*/: Range out of order in character class
    at new RegExp (<anonymous>)
    at a (JsBarcode.all.min.js:2)
    at e.default (JsBarcode.all.min.js:2)
    at new e (JsBarcode.all.min.js:2)
    at o (JsBarcode.all.min.js:2)
    at JsBarcode.all.min.js:2
```

Here is the HTML:

```
<html>
   <head>
      <script src="/Users/alan/Desktop/test/node_modules/jsbarcode/dist/JsBarcode.all.min.js"></script>
   </head>
   <body>
      <div>
         <canvas id="barcode-7c85145c-e64a-41ba-a0fe-dd4f97fa52c3"/>
      </div>
      <script>JsBarcode("#barcode-7c85145c-e64a-41ba-a0fe-dd4f97fa52c3", "this is code128",{format:"code128",lineColor:"#000",font:"monospace",width:2,height:80,displayValue:true});</script>
   </body>
</html>
```

**Comment by lindell** [comment] 2018-04-09 06:45
This is a problem with different charset between the html file and the JsBarcode file. Try specify `charset="UTF-8"` on the script tag and use `<meta charset="UTF-8">` in the head of the HTML

**Comment by lindell** [comment] 2018-04-09 06:45
Duplicate of: https://github.com/lindell/JsBarcode/issues/163

**Closed by lindell** 2018-04-09 06:45 UTC

**Comment by alanzhaonys** [comment] 2018-04-09 07:07
<meta charset="UTF-8"> did it for me. Thank you so much!

**Comment by cnganuruddha** [comment] 2021-01-18 06:28
This saved my day. Thank you.
