### ISSUE TITLE
barcode DPI is slow when print it to zebra GT820 barcode printer

### ISSUE THREAD

**Issue by softboy99** [lindell/JsBarcode#97] opened 2016-08-24 07:23 UTC
barcode DPI is slow when print it to zebra GT820 barcode printer

**Comment by lindell** [comment] 2016-08-24 08:44
I have no idea what the problem is. The DPI (Dots Per Inch) is slow? If you want any help please explain your problem in great detail.

**Comment by softboy99** [comment] 2016-08-26 01:33
the barcode is not clear enough, so the barcode scanner is not scanned easily. It can be scanned but not so easily.

**Comment by lindell** [comment] 2016-08-26 07:50
> in great detail

* What options are you using?
* On what platform (or all) does the problem occur.
* Does the problem only occur after printing or also before.
* Is the barcode blury? Does the line go together? If you don't know you could include an image.

And everything else that could be of relevance.

**Comment by softboy99** [comment] 2016-08-31 00:50
Hi
i use SVG. no any options, just use the sample code here:    $("#barcode").JsBarcode("some text here"); i also tried IMG AND Canvas. Both are the same. After that, i tried another library" jquery-barcode" plugin use its CSS mode, its ok.

**Comment by softboy99** [comment] 2016-08-31 00:52
In addition, when print it to large HP Printer, Its ok. The problem is the barcode printer. The maximum DPI of the barcode printer is 203.

**Comment by lindell** [comment] 2016-09-03 14:46
As you said. It seems to be the way the printer works that is the problem. It's strange that the "CSS mode" of jquery-barcode is working thou. I might add a third mode of printing the barcode information directly to the html in the future (CSS-mode). But for now I'm closing the issue

**Closed by lindell** 2016-09-03 14:46 UTC
Labels: Awaiting More Feedback

**Comment by adomguo** [comment] 2025-02-05 11:48
@lindell 
Hello. Do you solve this problem now? when i use 203dpi/300dpi. It is not scanned easily when i set width to 1

**Comment by lindell** [comment] 2025-02-05 12:42
Do you render to an svg or img tag. I would recommend svg.

**Comment by adomguo** [comment] 2025-02-06 01:26
@lindell 
I had rendered with svg. after 203/300 dpi printer printed it. it‘s scan will hard. width is 1.

**Comment by adomguo** [comment] 2025-02-06 01:29
@lindell what version do you had recmomend?
