### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by bruceCzK** [lindell/JsBarcode#76] opened 2016-06-06 06:08 UTC
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "jsbarcode"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.5
npm ERR! path /Users/chenzhuokai/Documents/Projects/WXBook-Node-Print/node_modules/jsbarcode/bin/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/chenzhuokai/Documents/Projects/WXBook-Node-Print/node_modules/jsbarcode/bin/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/chenzhuokai/Documents/Projects/WXBook-Node-Print/node_modules/jsbarcode/bin/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

And also use github url in package.json did't work.

Here is full error log.
[http://pastebin.com/tTRT6GK4](http://pastebin.com/tTRT6GK4)

**Comment by ChrisSFR** [comment] 2016-06-08 09:46
Same here
even some suggestions like:
npm cache clean 
creating an .npmignore file
install the newest version of node 6.2.1 and npm 3.9.6
couldn't solve the problem.

**Comment by lindell** [comment] 2016-06-08 11:38
I get the same when installing it from the npm repo but not locally. The file is there so I don't know what is causing this.

**Comment by ChrisSFR** [comment] 2016-06-08 11:53
tried a local npm install, but even there I get a ENOENT error :/
Can't figure out the cause, too.

**Comment by lindell** [comment] 2016-06-08 12:03
Tried to remove the cli.js in package.json but it now gives the error.

````
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/johan/DevZone/test/node_modules/jsbarcode/bin/barcodes'

````

**Comment by lindell** [comment] 2016-06-08 12:10
I think this is now fixed. (in 3.3.11). Can someone verify?

**Comment by ChrisSFR** [comment] 2016-06-08 12:16
worked for me, ty!

**Comment by nikolai-katkov** [comment] 2016-06-08 12:16
Working now (mac OS)

**Comment by lindell** [comment] 2016-06-08 12:20
Perfect! :smile: Closing the issue.

**Closed by lindell** 2016-06-08 12:20 UTC
Labels: Bug

**Comment by bruceCzK** [comment] 2016-06-12 02:31
@lindell Install works now, but can't be required in node.
```
Error: Cannot find module 'jsbarcode'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/chenzhuokai/Documents/Projects/WXBook-Node-Print/routes/orders.js:14:21
    at Object.<anonymous> (/Users/chenzhuokai/Documents/Projects/WXBook-Node-Print/routes/orders.js:186:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

and I think it is because of `"main": "./bin/JsBarcode.js"` in package.json, the file does not exist.

![image](https://cloud.githubusercontent.com/assets/8399711/15988582/c1311c8c-3088-11e6-8c52-8f2a174387bc.png)

**Comment by lindell** [comment] 2016-06-12 11:55
I removed `bin` from package.json since it did not install with it. I did now find the root of the problem. NPM is appearently using .gitignore to ignore files as well. Removed `bin` from it and things should work now.

**Comment by bruceCzK** [comment] 2016-06-12 13:46
Thanks, it works perfect now.
And I think I may find a "bug", if input is not a string, it will throw an error `string.substring is not a function`, maybe use a toString function and log a warning is a better solution.

**Comment by lindell** [comment] 2016-06-12 14:13
@bruceCzK I'm fixing this :+1:

**Comment by bruceCzK** [comment] 2016-06-12 14:14
Glad to help.

**Comment by lindell** [comment] 2016-06-12 14:17
6ff0b87b10d40589c81e76f4527ee85d7f08e84a Is fixing the problem. Added a test for it as well. Pushed as release `3.3.13`
