### ISSUE TITLE
Unencoded barcode label characters in production

### ISSUE THREAD

**Issue by alexmikhajlovic** [lindell/JsBarcode#430] opened 2023-04-08 04:06 UTC
I created a telegram bot that generates barcode, when I run locally the generated barcode label (String with barcode value under it) is encoded and printed correctly. However, when I run in production from an AWS Lightsail server the barcode value is still generated correctly but the label is not encoded and is printed with square characters.

*The project is server-side backend only and does not use the browser.*

<img width="475" alt="Screenshot 2023-04-07 at 21 01 08" src="https://user-images.githubusercontent.com/73855881/230702405-1826e162-d263-47fd-8aef-82dbb6920338.png">

<img width="475" alt="Screenshot 2023-04-07 at 21 01 21" src="https://user-images.githubusercontent.com/73855881/230702414-5e7546cf-b8f0-4ad9-891a-1f395701b071.png">

**Hope to find a solution!**

**Comment by lindell** [comment] 2023-04-08 05:07
Duplicate of #419 ?

**Comment by alexmikhajlovic** [comment] 2023-04-08 05:50
I have tried changing to a variety of available fonts available but the problem remains.

**Comment by lindell** [comment] 2023-04-08 05:51
You mean you have installed a variety of fonts on the system you are running it on?

**Comment by lindell** [comment] 2023-04-08 05:52
Do you mean you have installed a variety of fonts on the system you are running it on?

**Comment by alexmikhajlovic** [comment] 2023-04-08 21:15
I have the default fonts provided by the Lightsail server with MEAN stack.

**Comment by alexmikhajlovic** [comment] 2023-04-23 05:32
I actually needed to properly install fontconfig on the server, the problem was in cleaning up the cache before installation.

**Closed** 2023-04-23 05:32 UTC
